name: apriltag-renderer
version: git
summary: Render AprilTags.
description: >
  Render a tag:-
    $ apriltag-renderer --family tag36h11 --value 15 --size 300 --path tag36h11_15.png
  Render a tag with strange colors:-
    $ apriltag-renderer --family tag16h5 --value 0 --size 300 --black "#00FF00" --white "#FF00FF"
confinement: strict
parts:
  apriltag-renderer:
    plugin: nodejs
    node-engine: '10.14.1'
    source: .
apps:
  apriltag-renderer:
    command: apriltag-renderer
    plugs:
      - home
